apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas
  namespace: trident
spec:
  version: 1
  backendName: ontap-nas-backend
  storageDriverName: ontap-nas
  managementLIF: "192.168.1.100"           # ⚠️ CHANGE ME: NetApp Management IP (e.g., 10.50.10.100)
  dataLIF: "192.168.1.101"                 # ⚠️ CHANGE ME: NetApp Data LIF IP (e.g., 10.50.10.101)
  svm: "svm_name"                          # ⚠️ CHANGE ME: SVM name (e.g., svm_production)
  credentials:
    name: backend-tbc-ontap-nas-secret     # Reference to the secret
  storagePrefix: trident_                  # Prefix for volumes created by Trident
  limitAggregateUsage: "80%"               # Optional: limit aggregate usage
  limitVolumeSize: "500Gi"                 # Optional: max volume size
  nfsMountOptions: "nfsvers=4.1"          # NFS mount options
  defaults:
    spaceReserve: none
    snapshotPolicy: default
    snapshotReserve: "10"
    splitOnClone: "false"
    encryption: "false"
    unixPermissions: "0755"
    snapshotDir: "true"
    exportPolicy: default
    securityStyle: unix

---
# Configuration Notes:
# 
# Required fields to change:
# - managementLIF: Your NetApp cluster management IP (e.g., 10.0.0.10)
# - dataLIF: Your NetApp data network IP (e.g., 10.0.0.11) 
# - svm: Your Storage Virtual Machine name (e.g., svm_prod)
# - credentials.name: Must match the secret name created in secret.yaml
#
# After deployment, verify:
# kubectl get tbc -n trident
# kubectl get tridentbackends -n trident
# 
# Expected status: "Bound" or "Online"

