# Trident Backend Secret - Template
# ⚠️ DO NOT commit this file with real credentials to Git!
# This is a template only - replace with your actual NetApp credentials

apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-ontap-nas-secret
  namespace: trident
type: Opaque
stringData:
  username: "YOUR_NETAPP_USERNAME"      # ⚠️ CHANGE ME: NetApp admin username (e.g., admin)
  password: "YOUR_NETAPP_PASSWORD"      # ⚠️ CHANGE ME: NetApp admin password

---
# Instructions:
# 1. Copy this file to: secret.yaml (ignored by .gitignore)
# 2. Replace YOUR_NETAPP_USERNAME with real username
# 3. Replace YOUR_NETAPP_PASSWORD with real password  
# 4. Apply: kubectl apply -f secret.yaml
# 5. DO NOT commit secret.yaml to Git!

