apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-cluster-ca-for-certificates
spec:
  validationFailureAction: enforce
  background: true
  rules:

    # Rule 1: require all certificates to use cluster-ca
    - name: require-cluster-ca-issuer
      match:
        any:
          - resources:
              kinds:
                - Certificate
      validate:
        message: Certificates must use issuerRef.name=cluster-ca and issuerRef.kind=ClusterIssuer
        pattern:
          spec:
            issuerRef:
              name: cluster-ca
              kind: ClusterIssuer

    # Rule 2: block creation of new root CAs anywhere except cert-manager namespace
    - name: block-new-root-cas-outside-cert-manager
      match:
        any:
          - resources:
              kinds:
                - Certificate
      exclude:
        any:
          - resources:
              names:
                - cluster-root-ca
              namespaces:
                - cert-manager
      validate:
        message: Creating additional CA Certificates is not allowed. Use the central Root CA.
        deny:
          conditions:
            any:
              - key: "{{ request.object.spec.isCA }}"
                operator: Equals
                value: true
