apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-certificate-from-httproute
  labels:
    tls.automation/enabled: "false"
spec:
  validationFailureAction: Audit
  background: true

  rules:
    - name: generate-certificate-per-hostname

      preconditions:
        any:
          - key: "{{ request.object.metadata.labels.\"tls.automation/enabled\" }}"
            operator: Equals
            value: "true"

      match:
        any:
          - resources:
              kinds:
                - HTTPRoute

      generate:
        apiVersion: cert-manager.io/v1
        kind: Certificate
        name: "{{ request.object.metadata.name }}-tls"
        namespace: "{{ request.object.metadata.namespace }}"
        synchronize: true
        data:
          spec:
            secretName: "{{ request.object.metadata.name }}-tls"
            commonName: "{{ request.object.spec.hostnames[0] }}"
            dnsNames: "{{ request.object.spec.hostnames }}"
            issuerRef:
              name: cluster-ca
              kind: ClusterIssuer
