apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: my-redis
  namespace: platform
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.12
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
  nodeSelector:
    dedicated: tools
    node-type: tools

  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "tools"
      effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: dedicated
                operator: In
                values: ["tools"]
              - key: kubernetes.io/hostname
                operator: NotIn
                values: ["worker4", "worker5"]


  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: mayastor-3rep
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
