# =====================================================
# Kyverno: Add Gateway Parent Reference
# =====================================================
# 
# ⚙️ CONFIGURATION REQUIRED - Change Gateway name/namespace below
# 
# This policy automatically adds parentRefs to the Gateway for 
# HTTPRoute resources that don't have one specified.
#
# 📝 WHAT TO CHANGE:
#   Line 40: Change "samsung-gateway-fabric" to your Gateway name
#   Line 41: Change "nginx-gateway" to your Gateway namespace
#
# ⚠️ Leave as-is if using default Samsung Gateway
#
# =====================================================

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-gateway-parent-ref
  annotations:
    policies.kyverno.io/title: Add Gateway Parent Reference
    policies.kyverno.io/category: Convention over Configuration
    policies.kyverno.io/severity: low
    policies.kyverno.io/description: |
      Automatically adds parentRefs to samsung-gateway-fabric Gateway
      for HTTPRoute resources that don't have one specified.
      Works with NGINX Gateway Fabric (Gateway API).
      
      This is a safety policy that ensures all HTTPRoutes are connected
      to the Gateway, even if created manually or by other tools.
spec:
  background: true
  rules:
  - name: add-gateway-parent
    match:
      any:
      - resources:
          kinds:
          - HTTPRoute
    preconditions:
      all:
      # Only add if parentRefs is not already set
      - key: "{{request.object.spec.parentRefs[] | length(@)}}"
        operator: Equals
        value: 0
    mutate:
      patchStrategicMerge:
        spec:
          parentRefs:
          # ⚙️ CHANGE THIS: Gateway name and namespace (or leave default)
          - name: dcs-gateway-fabric  # ← CHANGE THIS LINE (or leave as-is)
            namespace: nginx-gateway       # ← CHANGE THIS LINE (or leave as-is)
            kind: Gateway

