apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-cluster-ca-for-certificates
  annotations:
    policies.kyverno.io/title: Enforce Cluster CA for cert-manager Certificates
    policies.kyverno.io/category: Security, TLS
    policies.kyverno.io/subject: Certificate, cert-manager
    policies.kyverno.io/description: |
      Ensures all cert-manager Certificates are issued by the central ClusterIssuer "cluster-ca".
      Prevents creating additional CAs outside the managed Root CA.
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: require-cluster-ca-issuer
      match:
        any:
          - resources:
              kinds:
                - Certificate
              apiGroups:
                - cert-manager.io
      validate:
        message: Certificates must use issuerRef.name=cluster-ca and issuerRef.kind=ClusterIssuer
        pattern:
          spec:
            issuerRef:
              name: cluster-ca
              kind: ClusterIssuer
    - name: block-new-root-cas-outside-cert-manager
      match:
        any:
          - resources:
              kinds:
                - Certificate
              apiGroups:
                - cert-manager.io
      exclude:
        any:
          - resources:
              namespaces:
                - cert-manager
              names:
                - cluster-root-ca
      validate:
        message: Creating additional CA Certificates is not allowed. Use the central Root CA.
        deny:
          conditions:
            any:
              - key: "{{ request.object.spec.isCA }}"
                operator: Equals
                value: true


