# RBAC Configuration for DEX Users
# Samsung Kubernetes Platform
---
# Admin user - full cluster access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: User
  name: admin@dcs.local  # From DEX email claim
  apiGroup: rbac.authorization.k8s.io
---
# Regular user - read-only access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-user-view-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: User
  name: user@dcs.local  # From DEX email claim
  apiGroup: rbac.authorization.k8s.io
---
# Example: Group-based access (when using LDAP/AD with groups)
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: oidc-admins-group-binding
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: cluster-admin
# subjects:
# - kind: Group
#   name: admins  # From DEX groups claim
#   apiGroup: rbac.authorization.k8s.io

